package com.pacman.environment;

/**
 * draws the number of maze and the pixels of each block
 * @author Royce de la Cruz
 */
public class Maze {
    // pixels of each block
    private final int ImageLength = 10;
    private final int ImageHeight = 10;
    // Maze number to draw
    static int n;

    public Maze(int numMaze) {
        Maze.n = numMaze;
    }

    /**
     * Blocks in the mazes
     */
    private final String MazeA[][][] = {{
        {"ESI", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "EII"},
        {"AR", "ME", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "DE", "DE", "DE", "DE", "DE", "DE", "ME", "ME", "DE", "DE", "DE", "DE", "DE", "DE", "ME", "AB"},
        {"AR", "AB", "1", "3", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "1", "3", "AR", "AB"},
        {"AR", "AB", "2", "4", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "EID", "CA", "CA", "CA", "CA", "2", "4", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESI", "EII", "CA", "CA", "CA", "CA", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "ESD", "EID", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "ESI", "EII", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "ME", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "ESD", "DE", "DE", "DE", "ME", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "AB", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"ESD", "EID", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESD", "DE", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "AB"},
        {"CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA"},
        {"CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA"},
        {"ESI", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "IZ", "IZ", "IZ", "EII", "CA", "CA", "AR", "ME", "IZ", "IZ", "IZ", "EII", "CA", "CA", "ESI", "EII"},
        {"AR", "ME", "DE", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "ME", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESI", "IZ", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "AB", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "AR", "AB", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "ME", "AB", "CA", "CA", "AR", "AB"},
        {"ESD", "EID", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "ESD", "EID", "CA", "CA", "ESD", "DE", "DE", "DE", "ME", "AB", "CA", "CA", "ESD", "EID"},
        {"CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA"},
        {"CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA"},
        {"ESI", "EII", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "AR", "AB", "CA", "CA", "ESI", "EII"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "DE", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "1", "3", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "1", "3", "AR", "AB"},
        {"AR", "AB", "2", "4", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "2", "4", "AR", "AB"},
        {"AR", "ME", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "ME", "ME", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "ME", "AB"},
        {"ESD", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "EID"}},
    {
        {"ESI", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "EII"},
        {"AR", "EID", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "ESD", "AB", "CA", "CA", "AR", "ME", "ME", "EID", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "ESD", "AB"},
        {"AR", "AB", "1", "3", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "1", "3", "AR", "AB"},
        {"AR", "AB", "2", "4", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "2", "4", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESI", "EII", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AR", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "IZ", "IZ", "IZ", "EII", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "ESD", "EID", "CA", "CA", "ESD", "EID", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "ESI", "IZ", "CA", "CA", "IZ", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "ESI", "EII", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "ESD", "DE", "CA", "CA", "DE", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "ESD", "DE", "ESD", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AR", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "AR", "ME", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AR", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "EII", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AR", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "ESD", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "ESI", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "IZ", "IZ", "IZ", "EID", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "ESI", "IZ", "CA", "CA", "IZ", "IZ", "IZ", "IZ", "IZ", "EID", "CA", "CA", "ESI", "EII", "ESI", "ESD", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "ESD", "DE", "CA", "CA", "DE", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "DE", "DE", "DE", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "ESD", "EII", "CA", "CA", "CA", "CA", "CA", "CA", "AB", "AR", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "IZ", "IZ", "IZ", "EII", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AR", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "AB"},
        {"AR", "AB", "1", "3", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "CA", "CA", "CA", "CA", "CA", "CA", "ESI", "EII", "CA", "CA", "CA", "CA", "1", "3", "AR", "AB"},
        {"AR", "AB", "2", "4", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "EII", "CA", "CA", "CA", "CA", "2", "4", "AR", "AB"},
        {"AR", "AB", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "ESI", "IZ", "IZ", "IZ", "IZ", "AB", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "ESI", "AB"},
        {"ESD", "EID", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "EID"}},
    {
        {"ESI", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "EII",},
        {"AR", "EID", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "ME", "ME", "ME", "ME", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "ME", "ME", "ME", "ME", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "AB",},
        {"AR", "AB", "1", "3", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ME", "ME", "ME", "ME", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ME", "ME", "ME", "ME", "CA", "CA", "CA", "CA", "1", "3", "AR", "AB",},
        {"AR", "AB", "2", "4", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "DE", "AR", "AB", "CA", "CA", "CA", "CA", "2", "4", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "IZ", "EII", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ESI", "EII", "CA", "CA", "CA", "CA", "ESI", "EII", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "AR", "ESI", "DE", "DE", "DE", "EID", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "ESI", "EII", "CA", "CA", "ESI", "IZ", "ME", "ME", "IZ", "EII", "CA", "CA", "AR", "AB", "ESI", "EII", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "ESD", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "IZ", "IZ", "IZ", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "ESD", "CA", "CA", "ESD", "EID", "CA", "CA", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "DE", "DE", "DE", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "ESI", "IZ", "IZ", "IZ", "AR", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "ESI", "EII", "CA", "CA", "ESI", "IZ", "IZ", "AB", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "IZ", "IZ", "AB", "CA", "CA", "ESI", "EII", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "ESD", "EID", "CA", "CA", "ESD", "DE", "DE", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "DE", "DE", "AB", "CA", "CA", "ESD", "EID", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "ESI", "EII", "CA", "CA", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "ESI", "EII", "AR", "AB", "AR", "EII", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "AB", "DE", "AB", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "ESD", "DE", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "ME", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "ESI", "AR", "AR", "AB", "CA", "CA", "ESI", "EII", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "ESD", "AR", "AR", "AB", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "ESD", "EID", "AR", "AB",},
        {"AR", "AB", "ESI", "EII", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "ESD", "EID", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "IZ", "IZ", "AB", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "AB", "AR", "EII", "CA", "CA", "AR", "IZ", "IZ", "AB", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "DE", "DE", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "AB", "AR", "EID", "CA", "CA", "AR", "DE", "DE", "AB", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "ESI", "EID", "AR", "ME", "ME", "AB", "CA", "CA", "ESI", "EII", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "AR", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "ESD", "EID", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "DE", "DE", "EID", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ESI", "EII", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "ME", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "EID", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "ESI", "EII", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "ESI", "AB", "ME", "ME", "ME", "ME", "ESI", "EII", "CA", "CA", "ESI", "EII", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "AR", "AB",},
        {"AR", "AB", "ESD", "EID", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "AR", "ME", "ME", "ME", "ME", "ME", "ME", "AB", "CA", "CA", "AR", "AB", "CA", "CA", "ESI", "ESI", "CA", "CA", "CA", "CA", "AR", "AB", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "ESD", "ME", "ME", "ME", "DE", "DE", "DE", "EID", "CA", "CA", "AR", "AB", "CA", "CA", "ESD", "EID", "CA", "CA", "CA", "CA", "AR", "AB", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "ESI", "EII", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "ESI", "EII", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "CA", "CA", "ESD", "EID", "DE", "DE", "DE", "EID", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "EID", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "EID", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "EID", "CA", "CA", "AR", "AB",},
        {"AR", "AB", "1", "3", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "ESI", "IZ", "IZ", "EII", "CA", "CA", "CA", "CA", "CA", "CA", "ESI", "EII", "CA", "CA", "CA", "CA", "CA", "CA", "ESI", "EII", "CA", "CA", "CA", "CA", "1", "3", "AR", "AB",},
        {"AR", "AB", "2", "4", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "ME", "ME", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "AR", "AB", "CA", "CA", "CA", "CA", "CA", "CA", "ESD", "EID", "CA", "CA", "CA", "CA", "2", "4", "AR", "AB",},
        {"AR", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "IZ", "AB",},
        {"ESD", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "DE", "EID",},}
    };
    /**
     * Series of the boolean values that determines where the maze is passable
     */
    private final boolean MazeF[][][] = {{
        {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
        {true, true, true, true, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, true, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, true, true, true, true},
        {true, true, true, true, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, true, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, true, true, true, true},
        {true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, true},
        {false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false},
        {true, true, true, true, true, true, true, true, false, false, true, true, true, true, false, false, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, true, true, true, true, true, true, false, false, true, true, true, true, false, false, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true},
        {true, true, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false},
        {true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, false, false, false, false, false, false, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, false, false, false, false, false, false, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, true},
        {true, true, true, true, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, true, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, true, true, true, true},
        {true, true, true, true, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, true, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, true, true, true, true},
        {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true}
    },
    {
        {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
        {true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true},
        {true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true},
        {true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, true, true, true, true, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, true, true, true, true, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true},
        {true, true, true, true, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, true, true, true, true},
        {true, true, true, true, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, true, true, true, true},
        {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true}},
    {
        {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,},
        {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,},
        {true, true, true, true, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true,},
        {true, true, true, true, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, true, false, false, false, false, true, true, false, false, true, true, false, false, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, true, false, false, false, false, true, true, false, false, true, true, false, false, true, true,},
        {true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true,},
        {true, true, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, true, true,},
        {true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, false, false, true, true, false, false, true, true, true, true, true, true,},
        {true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, false, false, true, true, false, false, true, true, true, true, true, true,},
        {true, true, false, false, false, false, false, false, true, true, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true,},
        {true, true, false, false, false, false, false, false, true, true, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, false, false, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, false, false, true, true, true, true, false, false, true, true, true, true, true, true, false, false, true, true, true, true, false, false, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, true,},
        {true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true,},
        {true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true, true,},
        {true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true,},
        {true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true,},
        {true, true, false, false, false, false, true, true, true, true, false, false, false, false, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true,},
        {true, true, false, false, false, false, true, true, true, true, false, false, false, false, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, false, false, true, true, true, true, false, false, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, true, true,},
        {true, true, false, false, false, false, true, true, true, true, false, false, true, true, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, true, true, false, false, true, true, false, false, true, true,},
        {true, true, false, false, false, false, true, true, true, true, false, false, true, true, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, true, true, false, false, true, true, false, false, true, true,},
        {true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true, false, false, false, false, false, false, false, false, true, true, true, true,},
        {true, true, true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true, false, false, false, false, false, false, false, false, true, true, true, true,},
        {true, true, false, false, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true, false, false, true, true, false, false, false, false, true, true, true, true,},
        {true, true, false, false, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true, false, false, true, true, false, false, false, false, true, true, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true,},
        {true, true, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, true, true,},
        {true, true, true, true, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, true, true, true, true,},
        {true, true, true, true, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, true, true, true, true,},
        {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,},
        {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,},}

    };
	/**
	 * Returns the length of the image
	 */
    public int ReturnLengthImages() {
    
        return ImageLength;
    }
    /**
	 * Returns the height of the image
	 */
    public int ReturnHeightImages() {
        return ImageHeight;
    }
    /**
	 * Returns the quantity of Row of the Maze
	 */
    public int ReturnAmountofRowsMaze() {
        return MazeA[n].length;
    }
    /**
	 * Returns the length of column of the Maze
	 */
    public int ReturnAmountofColumnsMaze() {
        return MazeA[n][0].length;
    }
    /**
   	 * Returns the image of the Maze
   	 */
    public String ReturnMazeImageCode(int Row, int Column) {
        return MazeA[n][Row][Column];
    }

    public String[][] MazeActual() {

        return MazeA[n];

    }
    public boolean[][] MazeFinal() {

        return MazeF[n];
    }

}
